### PR TITLE
Improve waypoints of the Blizzard NPC.

### PR DESCRIPTION
**Pull request by chaodhib**
- Fixes the waypoints of the npc controling the Blizzard

The only left to do now is ajust its speed since the distance of each cycle has been increased.

I generated about 200 way points, I can generate more if needed. I also intentionally made the npc fly so it's speed is constant all the time, maybe not a good thing to do?

Oh and, there is this small visual bug now: a part of the blizzard affect the upper side of Thorim's platform (maybe because the waypoint npc is flying about 5y about the floor)
wowscrnshot_082215_185122

Check here for a quick explanation on how I generated them: https://github.com/TrinityCore/TrinityCore/pull/15008#issuecomment-133727778. I can send you the files and scripts I used if you need.

### CODE REVIEW

**Comment by joschiwald** [comment]
nice to see someone is investigating the inital pr
but the best way to get these waypoints is to check sniffs

**Comment by chaodhib** [comment]
Oh, they can be found in the sniffs? Does the server send data about invisible Bunny NPCs or how does it work?

**Comment by joschiwald** [comment]
such invisible trigger npcs have invisible model, they appears in sniff like npcs with visible model

**Comment by chaodhib** [comment]
Well, too bad. Gonna copy past the small program in Java I wrote to generate the queries, for future reference just in case. It uses the library javaGeom 0.11.2.

``` Java
package thorimblizzard;

import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Collection;
import java.util.Locale;

import math.geom2d.Point2D;
import math.geom2d.conic.Circle2D;
import math.geom2d.line.StraightLine2D;

/**
 *
 * @author chaodhib
 */
public class ThorimBlizzard2 {

    // taken from extrapolation of data
    private static final double C2_Y=-61.33;
    private static final double CIRCLE1_RADIUS=32.5;
    private static final double CIRCLE2_RADIUS=37.0;

     // Curvilinear distance between each waypoint. decrease to generate more waypoints
    private static final double WPS_DELTA=1.0/3.0;

    private static final double DUMMY_ALTITUDE=421.0;

    public static void main(String[] args) {
        Point2D c1 = new Point2D(0, 0);
        Point2D c2 = new Point2D(0, C2_Y);

        Circle2D circle1 = new Circle2D(c1, CIRCLE1_RADIUS);
        Circle2D circle2 = new Circle2D(c2, CIRCLE2_RADIUS);

        // find the intersections between the 2 circles. pA should be on the right (positive x), pB on the left.
        Collection<Point2D> intersects = circle1.intersections(circle2);
        Point2D pA = (Point2D) (intersects.toArray()[0]);
        Point2D pB = (Point2D) (intersects.toArray()[1]);
        if (pA.getX() < pB.getX()) {
            Point2D swap = pA;
            pA = pB;
            pB = pA;
        }

        /**
         * First part: pA to pB by the circle2, in trigonometrical direction (counter clock-wise)
         */
        double angle = Math.atan((pA.getY() - c2.getY()) / (pA.getX() - c2.getX()));
//        System.out.println("angle: " + angle);

        int i = 1;
        Point2D p;
        boolean cdt;
        do {
            StraightLine2D line = new StraightLine2D(c2, angle);

            intersects = circle2.intersections(line);
            Point2D p1 = (Point2D) (intersects.toArray()[0]);
            Point2D p2 = (Point2D) (intersects.toArray()[1]);
            p = (p1.getY() > p2.getY()) ? p1 : p2;

            // this check allows for a smoth transition to the next part (no duplicate or uncorrectly ordered queries)
            if(p.getX() > pB.getX())
            {
                printSQLQuery(p, i);

                i++;
                angle += WPS_DELTA / circle2.radius();
            }

        } while (p.getX() > pB.getX());

        /**
         * Second part: pB to (0, circle1_radius) by circle1, anti trigo direction
         */
        angle = Math.atan((pB.getY() - c1.getY()) / (pB.getX() - c1.getX()))+Math.PI;
//        System.out.println("angle: "+angle);
        do {
        StraightLine2D line = new StraightLine2D(c1, angle);

        intersects = circle1.intersections(line);
        Point2D p1 = (Point2D) (intersects.toArray()[0]);
        Point2D p2 = (Point2D) (intersects.toArray()[1]);
        p = (p1.getX() <= 0.0) ? p1 : p2;

        printSQLQuery(p, i);

        i++;
        angle -= WPS_DELTA / circle1.radius();
        } while (angle>Math.PI/2);

        /*
        Third part: (0, circle1_radius) to pA by the circle1, anti trigo
        */
        double limitAngle=Math.atan((pA.getY() - c1.getY()) / (pA.getX() - c1.getX()));
//        System.out.println("Third and last part");
        angle = Math.PI/2;
//        System.out.println("angle: "+angle);
//        System.out.println("limitAngle: "+limitAngle);
        do {
        StraightLine2D line = new StraightLine2D(c1, angle);

        intersects = circle1.intersections(line);
        Point2D p1 = (Point2D) (intersects.toArray()[0]);
        Point2D p2 = (Point2D) (intersects.toArray()[1]);
        if(angle==Math.PI/2)
            p = (p1.getY() > 0.0) ? p1 : p2;
        else
            p = (p1.getX() >= 0.0) ? p1 : p2;

        printSQLQuery(p, i);

        i++;
        angle -= WPS_DELTA / circle1.radius();
        } while (angle>limitAngle);
    }

    private static void printSQLQuery(Point2D wayPoint, int index){
        DecimalFormat numFormat;
        String numberX, numberY;
        numFormat = new DecimalFormat(".###");
        numFormat.setDecimalFormatSymbols(DecimalFormatSymbols.getInstance(Locale.US));
        numberX = numFormat.format(wayPoint.getX() + 2134.877); //format and return to the original coordinate system
        numberY = numFormat.format(wayPoint.getY() - 263.118);

        // (@PATH,1,2125.243,-279.0981,419.6088,0,0,0,0,100,0),
        // (@PATH,603,2115.752,-263.1489,419.8545,0,0,0,0,100,0);
        System.out.println("(@PATH, " + index + ", "+numberX + ", " + numberY+", "+DUMMY_ALTITUDE+",0,0,0,0,100,0),");
    }

}
```

and
roomimage
roomimage4

**Pull request closed without merging**
